name: validate_commits

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize, reopened]

jobs:
  validate_commits:
    name: validate_commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Fetch all commits
        run: git fetch --prune --unshallow
      
      - name: Validate commit messages
        id: validate
        run: |
          valid_commit_regex='^(refactor|feature|feat|bugfix|docs|chore|bug|hotfix): .+\([A-Z]+-[0-9]+\) *$'
          echo "Using regex: $valid_commit_regex"
          commits=$(git log --pretty=format:"%s")
          invalid_commits=()
          while IFS= read -r commit_message; do
            if ! [[ "$commit_message" =~ $valid_commit_regex ]]; then
              invalid_commits+=("$commit_message")
              echo "Invalid commit message: $commit_message"
            fi
          done <<< "$commits"
          if [ ${#invalid_commits[@]} -gt 0 ]; then
            echo "Invalid commit messages found, please amend or rebase your branch."
            printf '%s\n' "${invalid_commits[@]}"
            exit 1
          else
            echo "All commit messages are valid."
          fi
        shell: bash
      
      - name: Report custom status for commits
        if: success()
        run: |
          echo "Setting fixed status context: validate_commits"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{
                     "state": "success",
                     "target_url": "'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'",
                     "description": "All commit messages are valid",
                     "context": "validate_commits"
                   }' \
               "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"
        shell: bash
